CREATE TABLE report_event (
    id              NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR2(60)   NOT NULL UNIQUE,
    tramite_id      NUMBER(19)     NOT NULL,
    tipo_id         NUMBER(19)     NOT NULL,
    estado_nuevo    VARCHAR2(20)   NOT NULL,
    event_timestamp TIMESTAMP      NOT NULL
);

CREATE INDEX idx_report_tramite ON report_event (tramite_id);
CREATE INDEX idx_report_tipo ON report_event (tipo_id);
